---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: client
spec:
 capacity:
   storage: 5Gi
 accessModes:
 - ReadWriteOnce
 storageClassName: standard
 hostPath:
   path: "/home/docker/1"

---
apiVersion: v1
kind: PersistentVolume
metadata:  
 name: data
spec:
 capacity:
   storage: 5Gi
 accessModes:   
 - ReadWriteOnce
 storageClassName: standard
 hostPath:
   path: "/home/docker/2"


---
apiVersion: v1
kind: PersistentVolume
metadata:  
 name: master
spec:
 capacity:
   storage: 5Gi
 accessModes:   
 - ReadWriteOnce
 storageClassName: standard
 hostPath:
   path: "/home/docker/3"
